### ISSUE TITLE
Premenovat vacsinu SYMFONY_ premennych

### ISSUE THREAD

**Issue by ostrolucky** [everlutionsk/symfony-docker#19]
Nazvy vacsiny environmentalnych premennych su zavadzajuce

SYMFONY_APP_PORT - toto je v skutocnosti len port ktory exposuje docker-compose pre nginx kontajner. Nginx kontajner nadalej interne pracuje s portom 80, rovnako tak symfony
SYMFONY_DB_PORT - to iste, je to len port ktory sa exposuje, v skutocnosti sa aplikacia pripaja furt na 3306
SYMFONY_APP_DOMAIN, SYMFONY_BASE_AUTH_USER, SYMFONY_BASE_AUTH_PASSWORD - nastavenie nginxu

Navrhovani kandidati:
DOCKER_NGINX_PORT
DOCKER_DB_PORT
NGINX_DOMAIN
NGINX_BASE_AUTH_USER
NGINX_BASE_AUTH_PASSWORD

**Comment by ivanbarlog** [comment]
agreed, could you create PR?

**Comment by ivanbarlog** [comment]
@ostrolucky please review the current master code I guess this has been already done
