### ISSUE TITLE
ENV Symfony parameters

### ISSUE THREAD

**Issue by ttibensky** [everlutionsk/symfony-docker#8]
- navrhujem vytvorit parameters.dev.yml a parameters.prod.yml, pripadne aj parameters.stg.yml
  - tieto subory budu obsahovat prevazne rovnaku konfiguraciu
- konfig ktory sa meni v zavislosti od environmentu navrhujem definovat komplet ako environment variables
  - napr db name user pass host port
  - teda nie len koli bezpecnosti pouzivat environment variables ale aj koli zjednodusenej konfiguracii inych environmentov. ked bude toto vsetko v environment variables tak na produkcii nebudes musiet robit novy deployment iba koli zmene parametrov
  - Ben to riesil v podprojekte roxhillu takto https://github.com/everlution/roxhill/blob/master/user/app/config/parameters.yml

**Comment by ostrolucky** [comment]
v symfony 4 je best practice .env, nie parameters.yml

**Comment by ivanbarlog** [comment]
resolved by using `infrastructure/env/symfony.env`
